=== anyilanxin/kunpeng-engine/kunpeng/bpm-model/xml-model/src/test/resources/com/anyilanxin/kunpeng/bpm/model/xml/testmodel/Testmodel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema elementFormDefault="qualified" attributeFormDefault="unqualified"
  xmlns="http://www.w3.org/2001/XMLSchema"
  xmlns:tns="https://anyilanxin.com/animals"
  targetNamespace="https://anyilanxin.com/animals">

  <element name="animals" type="tns:tAnimals"/>
  <complexType name="tAnimals">
    <sequence>
      <element name="description" type="string" minOccurs="0" maxOccurs="1" />
      <element ref="tns:animal" minOccurs="0" maxOccurs="unbounded" />
      <any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <element name="animal" type="tns:tAnimal"/>
  <complexType name="tAnimal" abstract="true" mixed="true">
    <sequence>
      <element ref="tns:relationshipDefinition" minOccurs="0" maxOccurs="unbounded"/>
      <element name="relationshipDefinitionRef" type="QName" minOccurs="0" maxOccurs="unbounded"/>
      <!-- for the alternative ns test we need the chance to have children from other namespaces -->
      <any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="id" type="ID"/>
    <attribute name="name" type="string"/>
    <attribute name="father" type="QName"/>
    <attribute name="mother" type="IDREF"/>
    <attribute name="isEndangered" type="boolean" default="false"/>
    <attribute name="gender" type="tns:tGender" use="required"/>
    <attribute name="age" type="integer"/>
    <attribute name="bestFriendRefs" type="IDREFS" />
    <anyAttribute namespace="##other" processContents="lax"/>
  </complexType>

  <element name="flyingAnimal" type="tns:tFlyingAnimal"/>
  <complexType name="tFlyingAnimal" abstract="true" mixed="true">
    <complexContent>
      <extension base="tns:tAnimal">
        <sequence>
          <element name="flightInstructor" type="IDREF" minOccurs="0" maxOccurs="1"/>
          <element name="flightPartnerRef" type="IDREF" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="wingspan" type="double" />
     </extension>
    </complexContent>
  </complexType>

  <element name="bird" type="tns:tBird" substitutionGroup="tns:animal"/>
  <complexType name="tBird" mixed="true">
    <complexContent>
      <extension base="tns:tFlyingAnimal">
        <sequence>
          <element ref="tns:egg" minOccurs="0" maxOccurs="6"/>
          <element name="spouseRef" type="QName" minOccurs="0" maxOccurs="1"/>
          <element name="guardEgg" type="IDREFS" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <element name="unknownAnimal" type="tns:tUnknownAnimal" substitutionGroup="tns:animal"/>
  <complexType name="tUnknownAnimal" mixed="true">
    <complexContent>
      <extension base="tns:tAnimal">
        <sequence>
          <element ref="tns:unknownAnimal" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="species" type="string" use="required"/>
        <attribute name="famous" type="boolean" default="false"/>
      </extension>
    </complexContent>
  </complexType>

  <simpleType name="tGender">
    <restriction base="string">
      <enumeration value="Unknown"/>
      <enumeration value="Male"/>
      <enumeration value="Female"/>
    </restriction>
  </simpleType>

  <element name="relationshipDefinition" type="tns:tRelationshipDefinition"/>
  <complexType name="tRelationshipDefinition" abstract="true">
    <attribute name="id" type="ID"/>
    <attribute name="animalRef" type="IDREF"/>
  </complexType>

  <element name="childRelationshipDefinition" type="tns:tChildRelationshipDefinition" substitutionGroup="tns:relationshipDefinition"/>
  <complexType name="tChildRelationshipDefinition">
    <complexContent>
      <extension base="tns:tRelationshipDefinition"/>
    </complexContent>
  </complexType>

  <element name="friendRelationshipDefinition" type="tns:tFriendRelationshipDefinition" substitutionGroup="tns:relationshipDefinition"/>
  <complexType name="tFriendRelationshipDefinition">
    <complexContent>
      <extension base="tns:tRelationshipDefinition"/>
    </complexContent>
  </complexType>

  <element name="egg" type="tns:tEgg"/>
  <complexType name="tEgg">
    <sequence>
      <element name="mother" type="tns:tAnimalReference" minOccurs="0" maxOccurs="1" />
      <element name="guardian" type="tns:tAnimalReference" minOccurs="0" maxOccurs="unbounded"/>
    </sequence>
    <attribute name="id" type="ID"/>
  </complexType>

  <complexType name="tAnimalReference">
    <attribute name="href" type="anyURI" use="required" />
  </complexType>

</schema>

=== anyilanxin/kunpeng-engine/kunpeng/bpm-model/xml-model/src/test/resources/com/anyilanxin/kunpeng/bpm/model/xml/testmodel/instance/UnknownAnimalTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<animals xmlns="https://anyilanxin.com/animals"
  xmlns:tns="https://anyilanxin.com/animals"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://anyilanxin.com/animals ../Testmodel.xsd ">

  <bird id="tweety" gender="Female">
    <childRelationshipDefinition id="tweety-hedwig" animalRef="hedwig"/>
    <friendRelationshipDefinition id="tweety-plucky" animalRef="plucky"/>
    <relationshipDefinitionRef>tweety-hedwig</relationshipDefinitionRef>
    <egg id="egg1"/>
    <egg id="egg2"/>
    <spouseRef>timmy</spouseRef>
  </bird>
  <bird id="hedwig" gender="Male"/>
  <bird id="birdo" gender="Female"/>
  <bird id="plucky" gender="Unknown"/>
  <unknownAnimal id="wanda" gender="Female" species="fish"/>
  <bird id="fiffy" gender="Female"/>
  <bird id="timmy" gender="Male"/>
  <unknownAnimal id="flipper" gender="Male" species="dolphin" famous="true"/>
  <bird id="daisy" gender="Female"/>
</animals>

=== anyilanxin/kunpeng-engine/kunpeng/bpm-model/xml-model/src/test/resources/com/anyilanxin/kunpeng/bpm/model/xml/type/child/ChildElementCollectionTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<animals xmlns="https://anyilanxin.com/animals"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://anyilanxin.com/animals ../../testmodel/Testmodel.xsd ">

  <bird id="tweety" gender="Female">
    <flightInstructor>daffy</flightInstructor>
    <flightPartnerRef>daisy</flightPartnerRef>
    <flightPartnerRef>plucky</flightPartnerRef>
  </bird>
  <bird id="daffy" gender="Male"/>
  <bird id="daisy" gender="Female"/>
  <bird id="plucky" gender="Male"/>
  <bird id="birdo" gender="Female"/>
</animals>

=== anyilanxin/kunpeng-engine/kunpeng/bpm-model/xml-model/src/test/resources/com/anyilanxin/kunpeng/bpm/model/xml/testmodel/instance/BirdTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<animals xmlns="https://anyilanxin.com/animals"
  xmlns:tns="https://anyilanxin.com/animals"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://anyilanxin.com/animals ../Testmodel.xsd ">

  <bird id="tweety" gender="Female">
    <egg id="egg1">
      <mother href="#tweety"/>
      <guardian href="#hedwig" />
      <guardian href="#timmy" />
    </egg>
    <egg id="egg2">
      <mother href="#tweety"/>
      <guardian href="#hedwig" />
      <guardian href="#timmy" />
    </egg>
    <egg id="egg3">
      <guardian href="#timmy" />
    </egg>
    <spouseRef>hedwig</spouseRef>
  </bird>
  <bird id="hedwig" gender="Male">
    <guardEgg>egg1</guardEgg>
    <guardEgg>egg2</guardEgg>
  </bird>
  <bird id="timmy" gender="Male">
    <guardEgg>egg1 egg2</guardEgg>
    <guardEgg>egg3</guardEgg>
  </bird>
</animals>

=== anyilanxin/kunpeng-engine/kunpeng/bpm-model/xml-model/src/test/resources/com/anyilanxin/kunpeng/bpm/model/xml/testmodel/instance/AnimalTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<animals xmlns="https://anyilanxin.com/animals"
  xmlns:tns="https://anyilanxin.com/animals"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://anyilanxin.com/animals ../Testmodel.xsd ">

  <bird id="tweety" gender="Female" bestFriendRefs="birdo plucky">
    <childRelationshipDefinition id="tweety-hedwig" animalRef="hedwig"/>
    <childRelationshipDefinition id="tweety-birdo" animalRef="birdo"/>
    <friendRelationshipDefinition id="tweety-plucky" animalRef="plucky"/>
    <friendRelationshipDefinition id="tweety-fiffy" animalRef="fiffy"/>
    <relationshipDefinitionRef>tweety-hedwig</relationshipDefinitionRef>
    <relationshipDefinitionRef>tweety-birdo</relationshipDefinitionRef>
    <relationshipDefinitionRef>tweety-plucky</relationshipDefinitionRef>
    <relationshipDefinitionRef>tweety-fiffy</relationshipDefinitionRef>
  </bird>
  <bird id="hedwig" gender="Male"/>
  <bird id="birdo" gender="Female"/>
  <bird id="plucky" gender="Unknown"/>
  <bird id="fiffy" gender="Female"/>
  <bird id="timmy" gender="Male"/>
  <bird id="daisy" gender="Female"/>
</animals>

=== anyilanxin/kunpeng-engine/kunpeng/bpm-model/xml-model/src/test/resources/com/anyilanxin/kunpeng/bpm/model/xml/testmodel/instance/FlyingAnimalTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<animals xmlns="https://anyilanxin.com/animals"
  xmlns:tns="https://anyilanxin.com/animals"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://anyilanxin.com/animals ../Testmodel.xsd ">

  <bird id="tweety" gender="Female">
    <flightInstructor>hedwig</flightInstructor>
    <flightPartnerRef>hedwig</flightPartnerRef>
    <flightPartnerRef>birdo</flightPartnerRef>
    <flightPartnerRef>plucky</flightPartnerRef>
    <flightPartnerRef>fiffy</flightPartnerRef>
  </bird>
  <bird id="hedwig" gender="Male"/>
  <bird id="birdo" gender="Female"/>
  <bird id="plucky" gender="Unknown"/>
  <bird id="fiffy" gender="Female"/>
  <bird id="timmy" gender="Male"/>
  <bird id="daisy" gender="Female"/>
</animals>
